on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VAULT_TEST_GITHUB_PAT: ${{ secrets.VAULT_TEST_GITHUB_PAT }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#installing-dependencies
        # If installing a development version of constellation, use:
        # - pip3 install git+https://github.com/reside-ic/constellation@reside-62#egg=constellation
        run: |
          python -m pip install --upgrade setuptools pip urllib3==1.26.11 wheel importlib-metadata
          python setup.py install --user
          pip3 install pytest-cov pycodestyle codecov

      - name: Tests
        run: |
          pytest --cov=src

      - name: Lint
        run: |
          pycodestyle . --exclude=.eggs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
